### ISSUE TITLE
Verzorger account

### ISSUE THREAD

**Issue by developingwild** [RickBakkr/SOMtoday#1]
Als ik inlog met een verzorger account, zie ik alleen maar het rooster van mij, niet van mijn broertje. Is er een specifieke methode hoe ik dit kan opvragen?

**Comment by RickBakkr** [comment]
Dag Niels,

Waardoor dat komt, zou ik zo niet weten. We zitten met de pech dat dit script grotendeels door iemand anders is geschreven. Ik zal er zo spoedig mogelijk voor je naar kijken :)

**Comment by niels515** [comment]
oke bedankt :)

**Comment by RickBakkr** [comment]
Zou je een mailtje kunnen sturen? M'n adres staat in de README

**Comment by RickBakkr** [comment]
Heb met Niels gesproken over de mail. Komt er naar mijn idee op neer dat er bij login() een bepaald ID wordt geset. Maar dit is altijd [0], dus de eerste in de array. Gaat het je om de 2e, bv. je broertje/zusje, dan moet dit [1] worden, etc.
 $pupilID  = (string) $response["leerlingen"][0]["leerlingId"];

Ik ga in de volgende versie kijken hoe ik dit kan verbeteren :+1:

**Comment by developingwild** [comment]
K ben nu nog druk bezig, zelfs in mn vakantie dus kan t nog niet testen :(
