### ISSUE TITLE
Gearchiveerd? 

### ISSUE THREAD

**Issue by MakerTim** [RickBakkr/SOMtoday#13]
Hey, 

Think this aint working anymore?
maybe time to archive this project then

**Comment by RickBakkr** [comment]
Hi Tim, 

You are correct. When SOMtoday 'updated' their mobile API, this wrapper became malfunctioning. There have since been plans to rewrite the wrapper to make the mobile API available via PHP/ other implementations again. Unfortunately, these never became reality. 

Meanwhile, I graduated from my 'middelbare school' and no longer have access to SOMtoday. It might be a good idea to do a write-up of the details on the API some fellas and I have obtained. Feel free to send me an e-mail when you need any details / help with this OAuth API.

Rick.

**Comment by MakerTim** [comment]
Oke, zie dat we hier beide Nederlands zijn, dus als je het niet erg vind ga ik verder door op Nederlands


Ik moet een tool maken, waarbij ik meerdere leerlingen hun cijfers kan exporteren met 1 druk op de knop
van elke leerling heb ik de inlog gegevens, maar ik kan nergens api documentatie vinden van de nieuwe versie
en de app is erg aangepast op wat jullie andere "issue" discussie, waarbij het niet duidelijk is hoe je het er uit haalt

context:
dit alles voor huiswerk klas, waarbij we makkelijker kunnen zeggen wie naar welke les moet
zonder voor elk kind in te loggen, kijken wat de (nieuwe) cijfers zijn, en vervolgens ze aanbeveling geven waar ze heen moeten

dus nu ~46 kiddo's handmatig bijhouden kost ~4uur in de week, wat niet te doen is, vandaar dat automatisatie nodig is
dit ging eerst via semi docent account, maar vanwege AVG onzin mogen we dat niet meer zo oplossen...
vandaar de iedereen hun wachtwoord opvragen en deze oplossing

**Comment by RickBakkr** [comment]
Da's prima hoor :) 

Oké, hier komt ie:
We beginnen met het ophalen van het unieke uuid van de instelling:
```
GET https://servers.somtoday.nl/organisaties.json
```
Vervolgens kan je gaan "inloggen":
```
POST https://production.somtoday.nl/oauth2/token
```
Deze behoeft volgende parameters:
`grant_type`, value: `password`
`username`, value: `<uuid>\<username>`
`password`, value: `<password>`
`scope`, value: `openid`
**HEADERS:**
`Accept`, value `application/json`
`Authorization`, value: 
```
Basic RDUwRTBDMDYtMzJEMS00QjQxLUExMzctQTlBODUwQzg5MkMyOnZEZFdkS3dQTmFQQ3loQ0RoYUNuTmV5ZHlMeFNHTkpY
```
**Dit is een "random" sleutel, die steeds constant is.. De sukkels dachten ons te slim af te zijn ;-)**

Je krijgt hier terug, een JSON array met access_token (die heb je nodig voor latere requests: zie Auth header), en api_url or somtoday_api_url (zoiets), dit is de base URL, dus die URL + /rest/v1/enzovoorts..

```
GET /rest/v1/resultaten/huidigVoorLeerling/<User ID>
```
Je geeft aan deze request verder mee als headers:
`Authorization`, value `Bearer <access token>`
`Accept`, value `application/json`

_Het kan heel goed zijn dat er iets niet klopt, is even gauw zoeken in een chatgeschiedenis.. Geef maar een gil - ook als het wél werkt. Thanks :-). Kan het helaas niet meer testen..._

**Comment by MakerTim** [comment]
Ga er morgen weer mee aan de slag, maar dit helpt enorm!

**Comment by MakerTim** [comment]
![image](https://user-images.githubusercontent.com/1375359/48257805-dbec2d00-e413-11e8-8a59-bf9a6f34a9ab.png)
Wat doe ik hier fout? ik krijg een 404...
*headers*
Accept:application/json
Authorization:Basic RDUwRTBDMDYtMzJEMS00QjQxLUExMzctQTlBODUwQzg5MkMyOnZEZFdkS3dQTmFQQ3loQ0RoYUNuTmV5ZHlMeFNHTkpY

**Comment by RickBakkr** [comment]
Geeft ie nog iets terug als Body?

**Comment by RickBakkr** [comment]
Oauth/today?? 
Is toch oauth/token als URI?

**Comment by MakerTim** [comment]
Oh, die typo had ik al opgelost :S 
maar lege body

probeer params en body form-data, maar beide krijg ik een 405 method not allowed

**Comment by MakerTim** [comment]
https://puu.sh/BYTcg.png

headers die ik terug krijg:
https://puu.sh/BYTct.png

**Comment by RickBakkr** [comment]
Kun je Content-Type: application/jaon eens toevoegen als header?

**Comment by MakerTim** [comment]
Geen verschil :(

**Comment by RickBakkr** [comment]
Heb je die andere typen formdata al geprobeerd? Ik zal vanmiddag thuis even kijken voor je....

**Comment by MakerTim** [comment]
alle 3 geprobeert, put/post/get
als params en als body data
>,< erg fustrerend dit

als ik je vanmiddag probeert kan ik je een login lenen (onder goed vertrouwen)

**Comment by RickBakkr** [comment]
Zou handig zijn! Je mag me wel even mailen op mail <at> rickbakker <puntje> eu

**Comment by MakerTim** [comment]
![image](https://user-images.githubusercontent.com/1375359/48261894-d6e1aa80-e420-11e8-8d89-2e4af864f645.png)
ben nu iets verder gekomen, krijg nu wel een body antwoord, maar hij zegt dat ik verkeerde grant gebruik
maar kan ook iets anders zijn heb ik het gevoel, want hij zegt Account 2 attempts remaining 
maar de 2 gaat nooit om hoog

**Comment by MakerTim** [comment]
Ik heb het werkend!

school_uuid='<<UUID>>' username='<<USERNAME>>' password='<<PASSWORD>>' && curl "https://production.somtoday.nl/oauth2/token"  -d "username=$school_uuid\\$username" -d "grant_type=password" -d"password=$password&scope=openid"  -H "Authorization: Basic RDUwRTBDMDYtMzJEMS00QjQxLUExMzctQTlBODUwQzg5MkMyOnZEZFdkS3dQTmFQQ3loQ0RoYUNuTmV5ZHlMeFNHTkpY" --silent

**Comment by MakerTim** [comment]
ps. postman is blijkbaar kapot in deze update; dus sorry voor het lastigvallen daarmee

**Comment by MakerTim** [comment]
wat is UserID? 🤔

**Comment by RickBakkr** [comment]
Probeer `GET /rest/v1/leerlingen` eens, ik denk dat je dan een array terugkrijgt met die user/ leerling?

**Comment by RickBakkr** [comment]
Zal de issue sluiten. Package is onderhand geupdatet naar de nieuwe API. :)
