### ISSUE TITLE
SOM update

### ISSUE THREAD

**Issue by remcopoulus** [RickBakkr/SOMtoday#14]
Sinds een update van SOM (net voor kerst) werkt mijn login script gebaseerd op deze code niet meer.
De https://school-elo.somtoday.nl/services/mobile/v10/Login/GetMD/user/pass/brin/
pagina geeft alleen "No service was found."

Edit: Daarom over naar de nieuwere optie (met dank aan Rick):
1. GET $uuid van https://servers.somtoday.nl/organisaties.json
`<?php
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
		$post_to = "https://production.somtoday.nl/oauth2/token";
		curl_setopt($ch, CURLOPT_URL, $post_to);
		curl_setopt($ch, CURLOPT_POST, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS,"grant_type=password&username=".$uuid."\\".$email."&password=".$password."&scope=openid");
RDUwRTBDMDYtMzJEMS00QjQxLUExMzctQTlBODUwQzg5MkMyOnZEZFdkS3dQTmFQQ3loQ0RoYUNuTmV5ZHlMeFNHTkpY
		curl_setopt($ch, CURLOPT_HTTPHEADER, Array(
			'Accept: application/json',
  			'Content-Type: application/x-www-form-urlencoded',
  			'Authorization: Basic RDUwRTBDMDYtMzJEMS00QjQxLUExMzctQTlBODUwQzg5MkMyOnZEZFdkS3dQTmFQQ3loQ0RoYUNuTmV5ZHlMeFNHTkpY'
		));
		$return = curl_exec($ch);
		curl_close ($ch);
		$results = json_decode($return);`

Je krijgt dus een JSON array terug voor verdere verwerking

**Comment by RickBakkr** [comment]
Hi Remco, 

Ben zelf sinds dit schooljaar geen middelbaar scholier meer. De door jou gelinkte URL lijkt heel sterk op de 'oude' API, kun je eens kijken of de volgende manier wel werkt voor je: https://github.com/RickBakkr/SOMtoday/issues/13#issuecomment-437159805

Je mag me anders ook wel eventjes per e-mail benaderen, kunnen we daar kijken naar een oplossing. :-)

**Comment by remcopoulus** [comment]
Komt dit mailtje aan?

**Comment by RickBakkr** [comment]
Neen, da's een antwoord op de mail van GitHub. mag naar _rickbakkr@gmail.com_.
