### ISSUE TITLE
Max 100 Resultaten

### ISSUE THREAD

**Issue by TwanHogervorst** [RickBakkr/SOMtoday#15]
Hey RickBakkr,

Ik ben zelf wat aan het experimenteren met jouw SomtodayAPI.
Ik ben voornamelijk bezig met het nabouwen van jouw API in C#, zodat ik het kan gebruiken in bv. desktop applicaties of Android/IPhone Apps.

Ik heb zelf geen inzage op het API systeem van Somtoday, dus vandaar dat ik jouw API als richtlijn gebruik.

Maar terwijl ik hiermee bezig was merkte ik op dat je maar 100 items terug krijgt als je getGrades() uitvoert. Waarschijnlijk geldt dit niet alleen voor de cijfers, maar voor alle requests doe je doet naar Somtoday.

Is het dus mogelijk om een range op te geven, waarvan je de cijfers wilt krijgen. (dus van 0 tot 100, van 100 tot 200, enz.)

**Comment by RickBakkr** [comment]
Hi Twan,

Zul je de mobiele app even moeten reverse-engineeren, zou het zou uit het hoofd niet weten.

-rick

**Comment by TwanHogervorst** [comment]
Bedankt voor je tip Rick!

Ik heb de app ge-reversed-engineerd en na een lange tijd zoeken heb ik de oplossing gevonden.
Het is eigenlijk heel logisch en jammer dat ik er zo lang over heb moeten doen maar het werkt zo:

Je stelt de HTTPRequest header Range in op een string in het formaat: `"items={LowerBound}-{UpperBound}"`. (Met alles tussen {} als variabele)

Als je wilt weten hoeveel items er totaal te verkrijgen zijn dan kan je die opvragen door de request te doen en dan de response header Content-Range parsen. Deze is in het formaat: `"items={LowerBound}-{UpperBound}/{TotalItems}"`. (De Content-Range krijg je alleen bij de response, je moet deze dus niet instellen bij een request. Gebruik voor de request ook niet deze vorm)

Hiermee is dus het range probleem opgelost en zou dit ook kunnen worden toegepast in de PHP-API.
Bij uitgebreidere programmeertalen (bij mij C#) is er vaak ook een functie die automatisch de header in de goede vorm zet (bv. bij C# kan je `HttpRequest.AddRange("items", int lowerbound, int upperbound)` gebruiken).

Een klein voorbeeldje hoe je de Range string opsteld:
```C#
int lowerbound = 150;
int upperbound = 175; //In totaal krijg je dus 25 items vanaf item 150 tot item 175
string rangeString = "items=" + lowerbound + "-" + upperbound; //Met deze string stel je de header in
```

**Comment by joosthoi1** [comment]
> "items={LowerBound}-{UpperBound}/{TotalItems}"

Hallo Twan,

Ik probeer dit na te doen in python, alleen ik begrijp nu nier helemaal wat ik bij de headers moet toevoegen, tot nu toe heb ik dit:
```py
r = requests.get(
    f'{url}/rest/v1/resultaten/huidigVoorLeerling/{id}',
    headers = {
        "Authorization": f"Bearer {auth}",
        "Accept": "application/json",
        "Range":"items={LowerBound}-{UpperBound}/{TotalItems}"
        }
    )
```
als ik nu `print(len(r.json()))` doe dan krijg ik een error, wat doe ik verkeerd?
```
{"code":400,"reason":"Bad Request","exception":"javax.ws.rs.BadRequestException","message":"RESTEASY003870: Unable to extract parameter from http request: javax.ws.rs.HeaderParam(\"Range\") value is {1} for public javax.ws.rs.core.Response nl.topicus.iridium.rest.resultaten.RResultaatResourceImpl.getHuidigVoorLeerling(long,nl.topicus.cobra.restcontract.http.RequestRange)","applicationErrorParameters":{}}```

**Comment by TwanHogervorst** [comment]
Hey Joost,

Ik had je privé al gesproken, maar heb mijn laatste bericht met de uitleg bijgewerkt.
Ik hoop dat het nu voor anderen ook duidelijk genoeg is.

**Comment by joosthoi1** [comment]
Hallo Twan,

Ja, hartstikke bedankt, alles werkt nu en kan ik weer verder.
Alleen een beetje jammer dat je per request maar 100 resultaten kan krijgen, lijkt me ook niet handig voor de servers van som.
