### ISSUE TITLE
Fatal error: Class 'SOMtodayAPI\Container' not found in "example.nl/public_html/som/vendor/rbakker/somtodayapi/src/SOMtodayAPI/SOMtoday.php"

### ISSUE THREAD

**Issue by ChielChiel** [RickBakkr/SOMtoday#16]
Hoi, ik ben al een aantal dagen aan het proberen om deze library werkende te krijgen op mijn webhost.

## Wat heb ik gedaan
Ik heb ingelogd via ssh in mijn web host. Daar heb ik `cd /public_html/som/` gedaan. Nu in de `som` directory heb ik de volgende command uitgevoerd: `composer require rbakker/somtodayapi:v2.x-dev` (Zonder het `:v2.x-dev` wilde hij niet werken). Nu ziet de `public_html` er als volgt uit:
```
- public_html
    - som
        - index.php
        - vendor
            - autoload.php
            - composer
            - php-curl-class
            - rbakker
                - somtodayapi
                    - src
                        - SOMtodayAPI
                            - (Execptions, Interfaces, Models, Container.php & SOMtoday.php)
          
```
in `/som/index.php/` zit het volgende script:
``` php
require("vendor/autoload.php");
//use SOMtodayAPI\SOMtoday; gaf de volgende error: 
// Fatal error: Uncaught Error: Class 'SOMtodayAPI\SOMtoday' not found in example.nl/public_html/som/index:12 Stack trace: #0 {main} thrown in example.nl/public_html/som/index on line 12
use SOMtodayAPI\SOMtodayAPI\SOMtoday;

$allSchools = SOMtoday::getSchools();
print_r($allSchools);
```
## Wat is de output
```
Fatal error: Class 'SOMtodayAPI\Container' not found in example.nl/public_html/som/vendor/rbakker/somtodayapi/src/SOMtodayAPI/SOMtoday.php on line 16

```

## Wat verwacht ik
Dat `$allSchools` alle scholen output en dus de hele library werkt.

Ik hoop dat ik nu alle benodigde informatie heb gegeven om deze vraag oplosbaar te maken.

Groet, 
Michiel

**Comment by ChielChiel** [comment]
Als ik `composer require rbakker/somtodayapi` (dus zonder `:v2.x-dev`) gebruik in de terminal, krijg ik de volgende foutmelding
```bash
[RuntimeException]                                                           
  No composer.json present in the current directory, this may be the cause of  
   the following exception.                                                    
                                                                               

                                                                               
  [InvalidArgumentException]                                                   
  Could not find a version of package rbakker/somtodayapi matching your minim  
  um-stability (stable). Require it with an explicit version constraint allow  
  ing its desired stability.      
```

**Comment by joosthoi1** [comment]
Ik ben geen php expert en heb deze repo alleen gebruikt om het van php te reverse engineren naar python en c#, maar volgensmij heb je hetzelfde probleem als dit: https://stackoverflow.com/questions/1179638/php-class-not-found

**Comment by ChielChiel** [comment]
> Ik ben geen php expert en heb deze repo alleen gebruikt om het van php te reverse engineren naar python en c#, maar volgensmij heb je hetzelfde probleem als dit: https://stackoverflow.com/questions/1179638/php-class-not-found

Bedankt voor je reactie, ik heb alles een aantal keer gecheckt maar het lijkt vooralsnog geen effect te hebben...

**Comment by Potherca** [comment]
@ChielChiel deze code _zou_ moeten werken:

```php
<?php

require('vendor/autoload.php');

$allSchools = \SOMtodayAPI\SOMtoday::getSchools();

var_dump($allSchools);
```

De reden dat het _niet_ werk kom doordat de `psr-4` definitie in de `autoload` sectie van de `composer.json` niet klopt.

Als je het "gewoon" wil laten werken kun je het beste [composer vragen de autoloader te vullen met een classmap](https://getcomposer.org/doc/03-cli.md#dump-autoload-dumpautoload-) (in plaats van de incorrecte PSR-4):

```sh
composer dump --optimize
```

De output geeft onderstaande waarschuwing, maar die kun je veilig negeren.

```
Generating optimized autoload files
Deprecation Notice: Class SOMtodayAPI\SOMtoday located in ./vendor/rbakker/somtodayapi/src/SOMtodayAPI/SOMtoday.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class SOMtodayAPI\Container located in ./vendor/rbakker/somtodayapi/src/SOMtodayAPI/Container.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Generated optimized autoload files containing 24 classes
```

Voor dit issue om gefixed te worden op een manier die PSR4 compliant is, zou de inhoud van de map  `rbakker/somtodayapi/src/SOMtodayAP/` moeten worden verplaats naar `rbakker/somtodayapi/src/`.
