### ISSUE TITLE
Scholen die niet in servers.somtoday.nl voorkomen

### ISSUE THREAD

**Issue by tschoffelen** [RickBakkr/SOMtoday#2]
Ik kwam er gisteren achter dat er een aantal scholen zijn die niet voorkomen in de lijst servers.somtoday.nl, maar wel toegang hebben tot SOMtoday. Voorbeeld hiervan is:

> Gooise Scholen Federatie: https://somtoday.nl/gsf

Dit heeft er waarschijnlijk mee te maken dat SOMtoday over is gegaan van hun mobiele app op alleen nog maar de responsive website, en de lijst op servers.somtoday.nl blijkbaar niet meer geupdated wordt. Iemand een oplossing hiervoor?

**Comment by RickBakkr** [comment]
Hoi Thomas,

Leuk om een issue te zien van iemand van Scholica, vind het een toffe ELO!
Het lijkt me dat het gaat om de BRIN, maar die kan je via Google toch vrij gemakkelijk vinden?
Typ "gooise scholen federatie brin" maar eens in op Google, en een paar resultaten verder zie ik al: 14SM. Dat lijkt me de juiste BRIN-code, **niet getest**.

Erg jammer, maar SOMtoday heeft de app nog wel altijd in de Play en App Store staan. Hoe kom je erbij dat ze overgaan/zijn overgegaan op de responsive website?
