### ISSUE TITLE
Als ik website open maak...

### ISSUE THREAD

**Issue by K4CZP3R** [RickBakkr/SOMtoday#3]
De pagina op 192.168.1.54 werkt niet

192.168.1.54 kan dit verzoek momenteel niet verwerken.
500

Mijn index.php
```
<?php
include 'somtoday.php';
$som = SOMtodayUser("-","-","-","-")
$som->changeHomeworkStatus("-","-", true)
?>
```

**Comment by RickBakkr** [comment]
Hoi,

Ik lijk iets te zijn vergeten. Plaats eens een puntkomma (;) adhter de )s, zodat je als volgt krijgt:
$som = SOMtodayUser();
$som->func();
