### ISSUE TITLE
Enige support voor profiel foto's?

### ISSUE THREAD

**Issue by christosk92** [RickBakkr/SOMtoday#5]
Ik vroeg me af of je misschien profiel foto's kan toevoegen?

**Comment by RickBakkr** [comment]
Hi Chris,

Nee, op dit moment is deze support er volgens mij in de mobiele API niet. Dit betekent natuurlijk niet dat ik er niet naar ga kijken. Het zou zeker leuk zijn om adhv de/ een officiele API dit wel te kunnen implementeren.

**Comment by christosk92** [comment]
@RickBakkr  ik heb even rondgekeken en zo te zien blijkt de profiel foto alleen beschikbaar te zijn al zit je in een  zogenaamde JSession. In java is dit heel makkelijk te doen, ik zit het nu te implementeren in C#.
Ik weet niet hoe het moet in php maar het zou fijn zijn als je daar even naar keek :)

**Comment by christosk92** [comment]
En de JSessionId zit in een cookie

**Comment by RickBakkr** [comment]
Hi Chris,

Bedankt voor de tip. Tof dat je zelf ook met een implementatie bezig bent! Ga er zsm mee bezig :-)

**Comment by christosk92** [comment]
@RickBakkr Kijk maar:
![capture](https://cloud.githubusercontent.com/assets/13438702/18228279/d7dfe7dc-7247-11e6-93e0-4efc4770d296.PNG)

**Comment by christosk92** [comment]
zo te zien zijn er 2 JSESSIONID's
1. Op de main pagina
2. Al klik je op de login button wordt er een gemaakt.
3. Al zit je op de main hub(rooster etc) Die heb je nodig voor de profiel foto
De markup van 3 ziet er ongeveer zo uit:
`XQUZ6vyvxBbgnjAtziqTgE3mCCVj6YUtItL6cyOh.som-jas1:sis-elo-2`

**Comment by christosk92** [comment]
@RickBakkr Dit is hoe ik het heb gedaan.
Ik heb een webview gesimuleerd in mijn app en met InvokeScript de gebruikersnaam en wacthwoord in te vullen en de knop inloggen te klikken. Die 'gesimuleerde' webview navigeert dan naar de home pagina en daar kan ik de cookie header van krijgen(JSESSIONID)

`                    await webView.InvokeScriptAsync("eval", new string[] { "document.getElementsByName('passwordFieldPanel:usernameFieldPanel:usernameFieldPanel_body:usernameField')[0].value='"+username+"';" });
                    await webView.InvokeScriptAsync("eval", new string[] { "document.getElementsByName('passwordFieldPanel:passwordFieldPanel_body:passwordField')[0].value='"+password+"';" });
                    await webView.InvokeScriptAsync("eval", new string[] { "document.getElementsByTagName('a')[0].click();" });`

**Comment by RickBakkr** [comment]
@christosk92 Dank. Probleem is echter dat dit niet zo gemakkelijk te simuleren is in PHP.

**Comment by christosk92** [comment]
@RickBakkr Ja dat begrijp ik. Ik heb het al momenteel gepubliceerd in mijn repo op github.(Somtoday10)
