### ISSUE TITLE
Werkt niet meer?

### ISSUE THREAD

**Issue by ApocalypsjeNL** [RickBakkr/SOMtoday#6]
Hallo,
Wanneer ik inlog via de api dan krijg ik een 404 error.
Hoe los ik dit op?

PHP code:
$som = new SOMtodayUser("*****", "******", "grundel", "18CR");

var_dump($som->getGrades());

HTML output:
Warning: file_get_contents(https://somtoday.nl/grundel/services/mobile/v10/Login/CheckMultiLoginB64/******/*******/18CR): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in C:\xampp\htdocs\som\somtoday.php on line 123

Warning: file_get_contents(Cijfers/GetMultiCijfersRecentB64/****//18CR/): failed to open stream: No such file or directory in C:\xampp\htdocs\som\somtoday.php on line 180
NULL

(heb de gebruikersnaam en wachtwoord vervangen naar ****)

**Comment by RickBakkr** [comment]
Hi,

Dit klopt. De api endpoints kloppen niet meer. Er wordt aan een nieuwe
versie gewerkt.

Groet,
Rick
Op ma 21 nov. 2016 om 08:42 schreef Niek Vincent <notifications@github.com>

**Comment by ApocalypsjeNL** [comment]
Enig idee wanneer die uitkomt?

**Comment by RickBakkr** [comment]
Helaas nog niet. Zal kijken of ik binnenkort de huidige versie kan fixen.

Groet,
Rick
Op ma 21 nov. 2016 om 09:40 schreef Niek Vincent <notifications@github.com>

**Comment by RickBakkr** [comment]
@ApocalypsjeNL Zou je mij een mailtje kunnen sturen hierover op rickbakkr[at]gmail[dot]com

**Comment by RickBakkr** [comment]
Dag Niek,

Heb de wrapper geüpdatet naar de nieuwe endpoints.
