### ISSUE TITLE
Alle cijfers

### ISSUE THREAD

**Issue by TGlev** [RickBakkr/SOMtoday#7]
Hoi,

Is er ook een manier om **alle** cijfers op te vragen in plaats van de cijfers van de laatste maand?

~Luca

**Comment by RickBakkr** [comment]
Hoi Luca,

Helaas niet. Wat je terugkrijgt is wat SOM teruggeeft. Je kunt bij die request helaas geen parameter hiervoor meegeven en de output beïnvloeden. 

Hoop zo je vraag te hebben kunnen beantwoorden. Zo niet, hoor ik dat graag!

Groeten,
Rick

**Comment by TGlev** [comment]
Dat is zeer jammer.

Ik werk namenlijk aan mijn eigen SOMtoday app en ik zou dolgraag de gemiddelde cijfers van leerlingen willen weergeven.

Denk je dat ik aan SOM kan vragen of ze het willen toevoegen...?

~Luca

**Comment by RickBakkr** [comment]
Denk niet dat het zin heeft. De API waarop deze wrapper is gebaseerd, is de API die SOM gebruikt voor haar eigen mobiele applicaties. Deze API heeft vanuit SOM dus (althans, dat lijkt mij) geen support. 

Mocht je mijn code gebruiken in jouw app, zou ik het overigens tof vinden als je mijn naam vermeldt 😄

**Comment by TGlev** [comment]
Hey, heb je de nieuwe SomToday leerling app gezien? Die heeft wel ondersteuning voor alle cijfers. Kan je dit aan jouw API toevoegen?

**Comment by RickBakkr** [comment]
Hoi Luca,

Nee, deze heb ik nog niet gezien. Ik zal in de aankomende dagen kijken wat ik kan doen!

Bedankt voor het doorgeven.

Rick

**Comment by TGlev** [comment]
https://play.google.com/store/apps/details?id=nl.topicus.somtoday.leerling

**Comment by TGlev** [comment]
Als je de app decompiled, lijkt het er op alsof ze een compleet nieuwe API gebruiken. /rest/v1/.....

**Comment by TGlev** [comment]
Klopt, dit is al een gigantische verbetering. Heb je al wat gevonden om alle cijfers op te vragen? @RickBakkr

**Comment by RickBakkr** [comment]
Hoi,

Nee, helaas nog geen tijd voor gehad. Natuurlijk ben je vrij om te helpen,
als je meer weet over de "nieuwe" api.

Groet,
Rick
Op do 16 mrt. 2017 om 16:00 schreef TGlev <notifications@github.com>

**Comment by TGlev** [comment]
Helaas, ik weet ook nog vrij weinig.

**Comment by christosk92** [comment]
Ik heb de app kunnen decompilen en heb wat gevonden. 

http://image.prntscr.com/image/dd9df29ff5ac4756a79607c9ff80d90c.png

` @GET("rest/v1/resultaten/huidigVoorLeerling/{id}")`

**Comment by RickBakkr** [comment]
Topper ben je @christosk92 !
Gezien mijn vakantie inmiddels ook weer is begonnen, hoop ik er in de loop van aankomende week eens goed naar te kunnen kijken.

**Comment by christosk92** [comment]
@RickBakkr Ik probeer nu te zoeken wat de base url is en wat id is.

**Comment by RickBakkr** [comment]
Top! Keep me in touch.

**Comment by christosk92** [comment]
@RickBakkr Blijkbaar werkt de app met oAuth 2.0 en hebben ze een client id en client_secret. allemaal te zien met het blote oog!

**Comment by TGlev** [comment]
@RickBakkr @christosk92 Is er ondertussen al wat nieuws te melden? :)

**Comment by RickBakkr** [comment]
Hey Luca,

Heb helaas nog geen tijd gehad om dieper in de nieuwe app te duiken.

Mijn excuses,

Rick
Op ma 8 mei 2017 om 11:25 schreef TGlev <notifications@github.com>

**Comment by christosk92** [comment]
Same here. Mijn hdd is vol. Ik had vrijdag een besteld via Amazon en komt vandaag aan. Dan kan ik er misschien naar kijken

**Comment by RubenNL** [comment]
ik hoop dat iemand het voor elkaar krijgt om de nieuwe app te gebruiken met (bijv. PHP), omdat de oude app sinds 12-5-2017 niet meer werkt.

**Comment by RickBakkr** [comment]
@RubenNL Goed dat je dat ook even vermeldt! Zet er een beetje meer druk achter. Zit er aan te denken om een groep te gaan vormen met gebruikers van deze API en zodoende een soort discussieplatform op te zetten. Het lijkt knap lastig om de nieuwe API te ontrafelen, helemaal zonder een meewerkende SOM natuurlijk.

**Comment by RubenNL** [comment]
als je een nieuwe token aanmaakt, wordt hij niet meer geaccepteerd door som.

MAAR de oude tokens werken nog wel.

**Comment by christosk92** [comment]
Hoi iedereen,
Ik heb geen tijd gehad om nog naar de app te kijken, omdat ik het heel erg druk had met het recoveren van lost data van mijn oude harde schijf en ik nog wat dingen moet maken voor een prive project. 

Ik zal er zo snel mogelik naar kijken,

**Comment by RubenNL** [comment]
ik heb nog wat doorgezocht, en als je niet uitlogt, blijft de oude app nog werken.

**Comment by christosk92** [comment]
Zo te zien krijg je de auth code door:

`   localAuthenticationApi.login(Base64.encodeToString(String.format("%s:%s", arrayOfObject).getBytes(Charset.forName("UTF-8")), 2), paramString1 + "\\" + paramString2, paramString3, "openid", "password").enqueue(new Callback(paramContext)`
    

localAuthenticaionApi = een init van  AuthenticationApi. 
`   AuthenticationApi localAuthenticationApi = (AuthenticationApi)RetrofitDispenser.getAuthenticationInstance().create(AuthenticationApi.class);`

Als je daar kijkt krijg je interface die een POST doet naar een url? die ik nergens kan vinden?

```
public abstract interface AuthenticationApi
{
  @FormUrlEncoded
  @Headers({"Accept: application/json"})
  @POST("/oauth2/token")
  public abstract Call<SOAuth2Response> login(@Header("Authorization") String paramString1, @Field("username") String paramString2, @Field("password") String paramString3, @Field("scope") String paramString4, @Field("grant_type") String paramString5);

  @FormUrlEncoded
  @Headers({"Accept: application/json"})
  @POST("/oauth2/token")
  public abstract Call<SOAuth2Response> refresh(@Field("grant_type") String paramString1, @Field("client_id") String paramString2, @Field("client_secret") String paramString3, @Field("refresh_token") String paramString4);
}

```

**Comment by christosk92** [comment]
Ik zit nu met POSTMan wat URLS te proberen die embedded zijn in de app.

**Comment by RubenNL** [comment]
Beste allemaal, ik ben er net achter gekomen dat deze app:

https://play.google.com/store/apps/details?id=nl.krudde.somtodayalert

precies doet wat ik/wij willen bereiken. je kan de apk unzippen en daarin staan de java bestanden die je kan gebruiken.

**Comment by Jorspons** [comment]
Hoi iedereen,
Ik vroeg me af of er een mogelijkheid is om de cijfers op te halen als de cijfers geblokkeerd zijn. Dit kon met de MySchool app, maar die doet het niet meer.

**Comment by TGlev** [comment]
Hallo!
Probleem is dat ikzelf niet meer kan testen, mijn school heeft vakantie en het SOM systeem is praktisch leeg. Als ik inlog, krijg ik ook niks meer te zien.

**Comment by RubenNL** [comment]
Mischien slechte vraag, maar heeft er iemand al een keer aan som gevraagd
om meewerkend?

Op 13 mei 2017 7:16 p.m. schreef "Rick Bakker" <notifications@github.com>:

**Comment by TGlev** [comment]
@RubenNL Ja. Ik heb een keer een e-mail naar SOM gestuurd. Ze hebben mij verteld dat ik naar de administratie en/of de technische afdeling van mijn school moest. 

Deze afdelingen wisten geen van beide wat ik wilde...

**Comment by christosk92** [comment]
@RubenNL Ik heb het ook aan mijn school gevraagd en die zeiden dat ze mij niet toegang willen geven omdat ik dan zogenaamd ook 'toegang' heb tot lerarenaccounts.(onzin natuurlijk)

**Comment by RickBakkr** [comment]
Scholen zijn inderdaad heel erg huiverig wat API-toegang betreft. Uiteindelijk slaat het nergens op, zolang wij alleen onze eigen data kunnen opvragen, zie ik niet waarom privacy hier in het geging zou komen, immers: dat is onze eigen keuze. Het mooiste zou zijn, als SOM 3rd-party applicaties zou ondersteunen dmv OAuth en de gebruiker dus zelf een app zou moeten authenticeren. Zie dit echter helaas niet gebeuren, betwijfel of het nog zin heeft om met een nieuwe versie van de PHP wrapper bezig te gaan in mijn laatste jaar op de middelbare school (dus ook laatste jaar als SOM-gebruiker)...

**Comment by TGlev** [comment]
@RickBakkr Ik denk dat er een heleboel andere mensen zeer veel profijt er van kunnen hebben. 

@christosk92 Heb je al wat uitgedokterd mbt de nieuwe API?

**Comment by RickBakkr** [comment]
@TGlev Als in... Dat zou dan bovendien de fout van de gebruiker zijn, als SOM een token zou uitgeven na authenticatie op basis van username en wachtwoord, zie ik niet in waarom de gebruiker geen toestemming zou hebben gegeven? Bovendien lijkt het me dat je dan puur de resultaten van die specifieke persoon kunt inzien?

@christosk92 Ben daar ook erg benieuwd naar. Zelf afgelopen weekend maar weer eens in de API gedoken, ben bijna zover dat we authenticatietokens kunnen aanvragen... Nu hopen dat de rest ook lukt.

**Comment by RickBakkr** [comment]
Net bezig gegaan met de authenticatie binnen de API. Helaas nog geen successen en ben eigenlijk een beetje huiverig nu ik zie het volgende terugkrijg:
```
{"error_description":"Invalid` grant: Account has 2 attempts remaining","error":"invalid_grant"}
```

Wat ik jullie kan vertellen:
De URL die we dienen te aan te roepen voor de OAuth authenticatie is als volgt (POST request):
https://productie.somtoday.nl/oauth2/token
Hierbij dienen we de volgende parameters te gebruiken:
```
username: deze bestaat uit de UUID van de instelling en de gebruikersnaam van de user, een "\\" ertussen.
password: het wachtwoord, mogelijk moet er een encoding op. Als plain wachtwoord faalt het. 
scope: "openid"
grant_type: "password"
```

De volgende headers:
```
Accept: "application/json"
Content-Type: "application/x-www-form-urlencoded"
Authorization: "Basic RDUwRTBDMDYtMzJEMS00QjQxLUExMzctQTlBODUwQzg5MkMyOnZEZFdkS3dQTmFQQ3loQ0RoYUNuTmV5ZHlMeFNHTkpY"
```

Deze authorisatietoken komt voort uit een Base64 encodering van "D50E0C06-32D1-4B41-A137-A9A850C892C2:vDdWdKwPNaPCyhCDhaCnNeydyLxSGNJX". 

Komt hieruit voort:
```
    private static final String CLIENT_ID = "D50E0C06-32D1-4B41-A137-A9A850C892C2";
    private static final String PRODUCTIE_CLIENT_SECRET = "vDdWdKwPNaPCyhCDhaCnNeydyLxSGNJX";
```
Hiermee wordt de Basic Authenticatie header gegenereerd:
```
"Basic " + Base64.encodeToString(String.format("%s:%s", new Object[]{OAuthTokenDispenser.getClientId(), OAuthTokenDispenser.getClientSecret()}).getBytes(Charset.forName(HttpRequest.CHARSET_UTF8)), 2)
```
----------------------------
Update:
We willen waarschijnlijk dit als Authenticatie header hebben:
"Basic RDUwRTBDMDYtMzJEMS00QjQxLUExMzctQTlBODUwQzg5MkMyOnZEZFdkS3dQTmFQQ3loQ0RoYUNuTmV5ZHlMeFNHTkpY"
```
String key = "D50E0C06-32D1-4B41-A137-A9A850C892C2:vDdWdKwPNaPCyhCDhaCnNeydyLxSGNJX";
byte[] b64 = Base64.getEncoder().encode(s.getBytes("UTF-8"));
System.out.println("encoded: " + new String(b64));
```
**Dus de gebruikte header klopte al... We dienen de error elders te zoeken.**

Mochten jullie zelf wat willen proberen met bovenstaande info, probeer het gerust! Alle hulp is welkom.
Succes, ik hoop wat van jullie te mogen horen!

**Comment by RickBakkr** [comment]
Zou het eventueel een idee zijn om een Skype groep/ Discord server te openen waar we gezamelijk de SOM API kunnen gaan ontdekken, @TGlev @christosk92 en iedereen die zich geroepen voelt. Hoor graag, dan open ik die!

**Comment by RickBakkr** [comment]
BINGO! De username header dient slechts een slash te hebben, geen twee. Kom er nu in :-)

**Comment by luca-panjer** [comment]
@RickBakkr Een discord server zou geweldig zijn! Voeg me maar toe: TGlev#5962

Ik ga zo ook even kijken of ik er in kom. Is het wachtwoord van de gebruiker gewoon plain text?

**Comment by RickBakkr** [comment]
@TGlev Ja. Doe ik zo. 
Ja, is plain text, kijk maar even in mijn development branch (niet develop!!) ;-)

**Comment by RickBakkr** [comment]
Voor hen die zich geroepen voelen: https://discord.gg/7yDMasx
Op dit moment laat ik eerst 10 aanmeldingen toe, zodra die zijn behaald gaan we verder met een nieuwe link. Wil het gecontroleerd uitvoeren.

**Comment by elisaado** [comment]
Heeyyy

Ik ben bezig met dit project namaken in Ruby (met credits ofc) en vroeg me ook af of er ondersteuning was om alle cijfers te krijgen. Op onze school gebruiken we Somtoday alleen maar voor cijfers dus da's wel erg handig :p, ik begrijp php wel, dus ik denk dat ik wel voor een implementatie kan zorgen door de apk te decompileren, of de url te gebruiken die @christosk92 uit de APK heeft gehaald (dankje!)

 @RickBakkr Ik voel me geroepen!
