### ISSUE TITLE
Vink werkt niet

### ISSUE THREAD

**Issue by TGlev** [RickBakkr/SOMtoday#8]
Hey,

Ik heb zojuist geprobeerd om mbv jouw code het huiswerkvinken te implementeren in mijn app maar het werkt niet. Dit is mijn url:
`
https://merewa-elo.somtoday.nl/services/mobile/v10/Agenda/Vink/<aToken>/<appointmentID>/<huiswerkID>/True`

Ik krijg een error 404 not found terug.
Enig idee waarom dit niet werkt?

~Luca

**Comment by RickBakkr** [comment]
Hi Luca, 

Roep je mijn code aan vanuit je app of heb je een eigen interface gebaseerd op mijn code? Zal er binnenkort even voor je naar kijken :-)

**Comment by TGlev** [comment]
Ja, dan werkt het. Bedankt.
